Fix artifacts pattern
`brew pr-pull` requires the artifacts to be called `bottles{,_*}`:

```
Error: No artifacts with the pattern `bottles{,_*}` were found!
```